### PR TITLE
Refactor and codebase reset

### PR DESCRIPTION
**Pull request by hunruh**
Revamping the code structure and ramping up for reimplementation with a better organized base. Git does not include empty directories, so please refer to the file structure documented in the README for more complete changes.

### CODE REVIEW

**Review by cndwng — COMMENTED** [review]
yee

**Comment by fawnwong** [comment]
Looks fine, do we have a backup of the current site somewhere or are we okay with just clearing everything? If we are I'll go ahead and close the request.

**Comment by julianohta** [comment]
Looks good!

**Comment by julianohta** [comment]
^ that was an accident

**Comment by hunruh** [comment]
@fawnwong the backup is the previous commits to GitHub... is that alright?

**Comment by fawnwong** [comment]
Yeah it probably is, I might just be a little paranoid about a kinda full wipe on the master branch. That's fine though, I'll go ahead and close.

**Comment by hunruh** [comment]
Yea let's not make a habit of doing this.

**Pull request closed without merging**
